api:
  name: "lu-sl-sfdc"
  id: "17817535"
  version: "v1"
  
https:
  path: "/api/${api.version}/*"
  host: "0.0.0.0"
  timeout: "5000" 
  port: "8082"
  #port: "443"
  private:
    port: "8092"
    
sfdc:
  username: "GuntisRubenis@lu.com"
  password: "Lutest2022"
  token: "41kC48dtXQwGeuzYgOsDaHpWQ"