api:
  name: "lu-sl-sfdc"
  id: "18019406"
  version: "v1"
  
https:
  path: "/api/${api.version}/*"
  host: "0.0.0.0"
  timeout: "5000" 
  port: "8082"
  #port: "443"
  private:
    port: "8092"
    
    
sfdc:
  username: "GuntisRubenis@lu.com"
  password: "Lutest2022"
  token: "cPfgSi4usy4xlWbSQT0pn9fWf"
  
sap:
  protocol: "HTTPS"
  host: "lu-sl-sap.us-e2.cloudhub.io"
  port: "443"
  basepath: "/api/v1"
  auth:
    username: "test"
    password: "test"