#%RAML 1.0 SecurityScheme
type: x-custom
description: enforcement of the client_id and client_secret security policy for API authorization
describedBy:
  headers:
    client_id:
      type: string
      description: Restricting the API access to only registered clients.   
    client_secret:
      type: string
      description: Restricting the API access to only registered clients. 